In [1]:
import pandas as pd

In [16]:
df = pd.read_csv("Cell_Painting_Median_Features_Median_doses.csv")

In [17]:
df = df.drop("index", axis=1)
df

,InChICode_standardised,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,...,Nuclei_Texture_Variance_DNA_5_0,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0
0,InChI=1S/C12H15N3O2S/c1-7(2)18-8-4-5-9-10(6-8)...,5.000000,1728.953125,-1.375000,-25.445312,-0.067918,-0.062396,0.0,0.026443,0.038767,...,-0.218573,0.314918,0.222859,0.280258,0.192997,0.144917,0.168085,-0.332871,-0.314733,-0.313477
1,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,-0.008796,...,-0.135188,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,0.010680,...,0.015253,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,-0.005632,...,-0.040388,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327
4,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,0.005312,...,0.041850,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30399,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,0.010464,...,-0.201503,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515
30400,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,-0.000637,...,-0.069652,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060
30401,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,0.013308,...,0.042933,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681
30402,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,0.006730,...,0.081551,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934
30403,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,0.000868,...,-0.076350,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447

In [18]:
# Ensure numeric format
df['Cells_Number_Object_Number'] = pd.to_numeric(df['Cells_Number_Object_Number'], errors='coerce')

# Drop missing values
df = df.dropna(subset=['Cells_Number_Object_Number'])

# Calculate the 5th percentile (left tail)
left_tail_cutoff = df['Cells_Number_Object_Number'].quantile(0.05)

# Get compounds in the bottom 5% (left tail)
left_tail_df = df[df['Cells_Number_Object_Number'] <= left_tail_cutoff]

print("Compounds in the left tail (lowest 5%):")
print(len(left_tail_df))

Compounds in the left tail (lowest 5%):
1521

In [19]:
df = df[~df.InChICode_standardised.isin(left_tail_df.InChICode_standardised.to_list())]
df

,InChICode_standardised,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,...,Nuclei_Texture_Variance_DNA_5_0,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0
1,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,-0.008796,...,-0.135188,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,0.010680,...,0.015253,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,-0.005632,...,-0.040388,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327
4,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,0.005312,...,0.041850,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907
5,InChI=1S/C17H13NO3/c1-18-13-5-3-2-4-12(13)15(1...,5.000000,-459.175781,-8.570312,2.820312,-0.005516,-0.000954,0.0,-0.005567,-0.007145,...,-0.107378,0.052843,-0.004288,0.025918,0.020560,0.004302,-0.008033,-0.056396,-0.026962,-0.039564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30399,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,0.010464,...,-0.201503,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515
30400,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,-0.000637,...,-0.069652,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060
30401,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,0.013308,...,0.042933,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681
30402,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,0.006730,...,0.081551,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934
30403,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,0.000868,...,-0.076350,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447

In [20]:
import pandas as pd
from pandarallel import pandarallel

# Initialize pandarallel
pandarallel.initialize()

# Assuming you have a large dataframe 'df'
# Define the target column
target_column = 'Cells_Number_Object_Number'

# Function to calculate correlation
def calculate_correlation(column):
    if column == target_column:
        return 1
    subset = df[[target_column, column]].dropna()
    if subset.shape[0] > 1:
        return subset.corr().iloc[0, 1]
    else:
        return None

# Apply the function in parallel
correlations = df.columns[1:].to_series().parallel_apply(calculate_correlation)

# Filter columns with high correlation (absolute value > 0.8)
highly_correlated_columns = correlations[correlations > 0.8].dropna().index.tolist()

# Print the highly correlated columns
print(highly_correlated_columns)

INFO: Pandarallel will run on 40 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
['Cells_Neighbors_FirstClosestObjectNumber_5', 'Cells_Neighbors_FirstClosestObjectNumber_Adjacent', 'Cells_Neighbors_SecondClosestObjectNumber_5', 'Cells_Neighbors_SecondClosestObjectNumber_Adjacent', 'Cells_Number_Object_Number', 'Cells_Parent_Nuclei', 'Cells_Texture_DifferenceEntropy_DNA_10_0', 'Cells_Texture_DifferenceEntropy_DNA_3_0', 'Cells_Texture_DifferenceEntropy_DNA_5_0', 'Cells_Texture_Entropy_DNA_10_0', 'Cells_Texture_Entropy_DNA_3_0', 'Cells_Texture_Entropy_DNA_5_0', 'Cells_Texture_SumAverage_DNA_10_0', 'Cells_Texture_SumAverage_DNA_3_0', 'Cells_Texture_SumAverage_DNA_5_0', 'Cells_Texture_SumEntropy_DNA_10_0', 'Cells_Texture_SumEntropy_DNA_3_0', 'Cells_Texture_SumEntropy_DNA_5_0', 'Cytoplasm_Number_Object_Number', 'Cytoplasm_Parent_Cells', 'Cytoplasm_Parent_Nuclei', 'Nuclei_Neighbors_FirstClosestObjectNumber_1', 'Nuclei_Neighbors_SecondClosestObjectNumber_1', 'Nuclei_Number_Object_Number']

In [21]:
df_cleaned = df.drop(columns=highly_correlated_columns, axis=1)

,InChICode_standardised,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,...,Nuclei_Texture_Variance_DNA_5_0,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0
1,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,-0.008796,...,-0.135188,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,0.010680,...,0.015253,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,-0.005632,...,-0.040388,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327
4,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,0.005312,...,0.041850,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907
5,InChI=1S/C17H13NO3/c1-18-13-5-3-2-4-12(13)15(1...,5.000000,-459.175781,-8.570312,2.820312,-0.005516,-0.000954,0.0,-0.005567,-0.007145,...,-0.107378,0.052843,-0.004288,0.025918,0.020560,0.004302,-0.008033,-0.056396,-0.026962,-0.039564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30399,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,0.010464,...,-0.201503,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515
30400,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,-0.000637,...,-0.069652,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060
30401,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,0.013308,...,0.042933,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681
30402,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,0.006730,...,0.081551,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934
30403,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,0.000868,...,-0.076350,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447

In [22]:
df_cleaned = df_cleaned.reset_index(drop=True)
df_cleaned

,InChICode_standardised,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,...,Nuclei_Texture_Variance_DNA_5_0,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0
0,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,-0.008796,...,-0.135188,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673
1,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,0.010680,...,0.015253,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,-0.005632,...,-0.040388,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,0.005312,...,0.041850,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907
4,InChI=1S/C17H13NO3/c1-18-13-5-3-2-4-12(13)15(1...,5.000000,-459.175781,-8.570312,2.820312,-0.005516,-0.000954,0.0,-0.005567,-0.007145,...,-0.107378,0.052843,-0.004288,0.025918,0.020560,0.004302,-0.008033,-0.056396,-0.026962,-0.039564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28878,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,0.010464,...,-0.201503,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515
28879,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,-0.000637,...,-0.069652,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060
28880,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,0.013308,...,0.042933,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681
28881,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,0.006730,...,0.081551,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934
28882,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,0.000868,...,-0.076350,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447

In [26]:
df_cleaned.to_parquet("Cell_Painting_no_cellcount_confounder_dataset/Bray_etal_Cell_Painting_no_cellcount_confounder_dataset.parquet", index=False)

In [27]:
df_cleaned

,InChICode_standardised,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,Cells_AreaShape_FormFactor,...,Nuclei_Texture_Variance_DNA_5_0,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0
0,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,-0.008796,...,-0.135188,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673
1,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,0.010680,...,0.015253,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,-0.005632,...,-0.040388,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,0.005312,...,0.041850,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907
4,InChI=1S/C17H13NO3/c1-18-13-5-3-2-4-12(13)15(1...,5.000000,-459.175781,-8.570312,2.820312,-0.005516,-0.000954,0.0,-0.005567,-0.007145,...,-0.107378,0.052843,-0.004288,0.025918,0.020560,0.004302,-0.008033,-0.056396,-0.026962,-0.039564
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28878,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,0.010464,...,-0.201503,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515
28879,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,-0.000637,...,-0.069652,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060
28880,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,0.013308,...,0.042933,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681
28881,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,0.006730,...,0.081551,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934
28882,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,0.000868,...,-0.076350,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447