In [1]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.read_csv("../Cell_Painting_Median_Features_Median_doses.csv")
df

,InChICode_standardised,index,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,...,Nuclei_Texture_Variance_DNA_5_0,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0
0,InChI=1S/C12H15N3O2S/c1-7(2)18-8-4-5-9-10(6-8)...,960.0,5.000000,1728.953125,-1.375000,-25.445312,-0.067918,-0.062396,0.0,0.026443,...,-0.218573,0.314918,0.222859,0.280258,0.192997,0.144917,0.168085,-0.332871,-0.314733,-0.313477
1,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,1036.0,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,...,-0.135188,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4942.5,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,...,0.015253,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4944.5,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,...,-0.040388,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327
4,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4949.5,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,...,0.041850,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30399,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,30588.0,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,...,-0.201503,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515
30400,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,30589.0,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,...,-0.069652,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060
30401,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,30590.0,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,...,0.042933,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681
30402,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,30591.0,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,...,0.081551,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934
30403,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,30592.0,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,...,-0.076350,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447

In [4]:
import pandas as pd
from rdkit import Chem

# Function to convert InChI to SMILES
def inchi_to_smiles(inchi):
    try:
        mol = Chem.inchi.MolFromInchi(inchi)
        if mol:
            return Chem.MolToSmiles(mol)
    except:
        return None

# Apply conversion to the column
df['SMILES'] = df['InChICode_standardised'].apply(inchi_to_smiles)
df

[10:16:58] WARNING: not removing hydrogen atom without neighbors
[10:16:58] WARNING: not removing hydrogen atom without neighbors

,InChICode_standardised,index,Metadata_mmoles_per_liter,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,Cells_AreaShape_Compactness,Cells_AreaShape_Eccentricity,Cells_AreaShape_EulerNumber,Cells_AreaShape_Extent,...,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0,SMILES
0,InChI=1S/C12H15N3O2S/c1-7(2)18-8-4-5-9-10(6-8)...,960.0,5.000000,1728.953125,-1.375000,-25.445312,-0.067918,-0.062396,0.0,0.026443,...,0.314918,0.222859,0.280258,0.192997,0.144917,0.168085,-0.332871,-0.314733,-0.313477,COC(O)=Nc1nc2ccc(SC(C)C)cc2[nH]1
1,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,1036.0,5.000000,-272.074219,11.464844,-1.628906,-0.001808,-0.006674,0.0,-0.001405,...,0.023860,-0.016903,-0.017773,-0.028029,-0.038308,-0.041455,-0.070389,-0.067789,-0.071673,COCc1nc2c(=O)n(C)c(=O)n(CC(C)C)c2[nH]1
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4942.5,4.973595,101.958984,15.673828,-2.314453,0.010687,0.013397,0.0,-0.003746,...,-0.014119,0.035703,0.016875,-0.039304,-0.070028,-0.062892,-0.015647,-0.038908,-0.026464,CNC[C@H]1OCc2cnnn2CCCC(=O)N([C@H](C)CO)C[C@@H]1C
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4944.5,4.912934,-109.708984,-10.203125,1.718750,0.025025,0.014627,0.0,-0.007164,...,0.046218,0.031759,0.037029,-0.051411,-0.083061,-0.071562,-0.024598,-0.052021,-0.043327,CNC[C@@H]1OCc2cnnn2CCCC(=O)N([C@@H](C)CO)C[C@H]1C
4,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,4949.5,5.012874,-234.222656,8.873047,3.308594,0.010192,0.005251,0.0,-0.003173,...,-0.072889,-0.030955,-0.037623,-0.009460,0.004604,-0.010465,-0.031869,-0.025910,-0.014907,CNC[C@@H]1OCc2cnnn2CCCC(=O)N([C@H](C)CO)C[C@H]1C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30399,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,30588.0,5.000000,-226.027344,-18.847656,-0.511719,-0.005827,0.004864,0.0,0.003590,...,-0.114357,-0.123664,-0.127474,-0.069665,-0.056972,-0.044186,-0.019668,-0.091541,-0.062515,NNC(S)=Nc1cccc(-c2nnc(S)o2)c1
30400,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,30589.0,5.000000,254.769531,18.886719,-3.589844,0.027814,0.016943,0.0,-0.000781,...,-0.079942,-0.018155,-0.017759,-0.118369,-0.046322,-0.023926,0.033498,0.051214,0.016060,OCc1c[nH]c2ccccc12
30401,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,30590.0,5.000000,238.574219,-0.699219,6.625000,0.005228,0.008800,0.0,0.002336,...,-0.107812,-0.107077,-0.138399,0.168811,0.216703,0.195851,-0.063656,-0.042877,-0.071681,Nc1cccc(/C=C/C(=O)O)c1
30402,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,30591.0,5.000000,-238.945312,5.476562,0.089844,0.018032,0.012711,0.0,-0.004635,...,-0.070647,-0.095379,-0.102060,0.023423,0.049321,0.041996,0.023470,0.058959,0.065934,CC(=O)CSc1ccc(C(=O)O)cn1
30403,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,30592.0,5.000000,286.488281,0.589844,-3.125000,0.018058,0.007385,0.0,-0.002819,...,-0.035772,-0.069146,-0.038609,-0.023672,-0.021189,-0.042713,0.020877,0.020216,0.045447,COc1cc(C=O)c([N+](=O)[O-])cc1OC

In [6]:
df = df[["InChICode_standardised", "SMILES", "Cells_Number_Object_Number"]]
df

,InChICode_standardised,SMILES,Cells_Number_Object_Number
0,InChI=1S/C12H15N3O2S/c1-7(2)18-8-4-5-9-10(6-8)...,COC(O)=Nc1nc2ccc(SC(C)C)cc2[nH]1,-26.265625
1,InChI=1S/C12H18N4O3/c1-7(2)5-16-10-9(11(17)15(...,COCc1nc2c(=O)n(C)c(=O)n(CC(C)C)c2[nH]1,4.812500
2,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,CNC[C@H]1OCc2cnnn2CCCC(=O)N([C@H](C)CO)C[C@@H]1C,-2.435547
3,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,CNC[C@@H]1OCc2cnnn2CCCC(=O)N([C@@H](C)CO)C[C@H]1C,0.964844
4,InChI=1S/C16H29N5O3/c1-12-9-20(13(2)10-22)16(2...,CNC[C@@H]1OCc2cnnn2CCCC(=O)N([C@H](C)CO)C[C@H]1C,2.212891
...,...,...,...
30399,InChI=1S/C9H9N5OS2/c10-12-8(16)11-6-3-1-2-5(4-...,NNC(S)=Nc1cccc(-c2nnc(S)o2)c1,2.714844
30400,InChI=1S/C9H9NO/c11-6-7-5-10-9-4-2-1-3-8(7)9/h...,OCc1c[nH]c2ccccc12,-10.828125
30401,InChI=1S/C9H9NO2/c10-8-3-1-2-7(6-8)4-5-9(11)12...,Nc1cccc(/C=C/C(=O)O)c1,-0.078125
30402,InChI=1S/C9H9NO3S/c1-6(11)5-14-8-3-2-7(4-10-8)...,CC(=O)CSc1ccc(C(=O)O)cn1,-0.078125
30403,InChI=1S/C9H9NO5/c1-14-8-3-6(5-11)7(10(12)13)4...,COc1cc(C=O)c([N+](=O)[O-])cc1OC,-6.304688

In [7]:
# Ensure numeric format
df['Cells_Number_Object_Number'] = pd.to_numeric(df['Cells_Number_Object_Number'], errors='coerce')

# Drop missing values
df = df.dropna(subset=['Cells_Number_Object_Number'])

# Calculate the 5th percentile (left tail)
left_tail_cutoff = df['Cells_Number_Object_Number'].quantile(0.05)

# Get compounds in the bottom 5% (left tail)
left_tail_df = df[df['Cells_Number_Object_Number'] <= left_tail_cutoff]

print("Compounds in the left tail (lowest 5%):")
print(left_tail_df[['InChICode_standardised', 'SMILES', 'Cells_Number_Object_Number']])

Compounds in the left tail (lowest 5%):
                                  InChICode_standardised  \
0      InChI=1S/C12H15N3O2S/c1-7(2)18-8-4-5-9-10(6-8)...
135    InChI=1S/C26H39N5O5/c1-19-14-30(20(2)17-32)25(...
180    InChI=1S/C30H36FN3O5/c1-34-25-12-11-23(16-28(3...
184    InChI=1S/C30H36FN3O5/c1-34-25-12-11-23(16-28(3...
185    InChI=1S/C30H36FN3O5/c1-34-25-12-11-23(16-28(3...
...                                                  ...
30328  InChI=1S/C9H5ClINO/c10-6-4-7(11)9(13)8-5(6)2-1...
30329  InChI=1S/C9H5ClN4/c10-7-2-1-3-8(4-7)13-14-9(5-...
30339  InChI=1S/C9H6N2O2/c12-8-4-3-7(11-13)6-2-1-5-10...
30356  InChI=1S/C9H7F9N4OS/c1-2-6(8(13,14)15,9(16,17)...
30381  InChI=1S/C9H9BrN2O3S/c10-9-8(12(14)15)7-5(16-9...

                                                  SMILES  \
0                       COC(O)=Nc1nc2ccc(SC(C)C)cc2[nH]1
135    C[C@@H]1CN([C@H](C)CO)C(=O)CCCn2nncc2CO[C@H]1C...
180    CN1C(=O)c2cc(N=C(O)c3cccc(F)c3)ccc2OC[C@H]2O[C...
184    CN1C(=O)c2cc(N=C(O)c3cccc(F)c3)ccc2OC[C@@H]2O[...
185    CN1C(=O)c2cc(N=C(O)c3cccc(F)c3)ccc2OC[C@@H]2O[...
...                                                  ...
30328                             Oc1c(I)cc(Cl)c2cccnc12
30329                           N#CC(C#N)=NNc1cccc(Cl)c1
30339                               O=Nc1ccc(O)c2ncccc12
30356    CCC(NC(O)=Nc1nnc(C(F)(F)F)s1)(C(F)(F)F)C(F)(F)F
30381                O=[N+]([O-])c1c(Br)sc2c1N=C(O)CCCC2

       Cells_Number_Object_Number
0                      -26.265625
135                    -15.054688
180                    -18.148438
184                    -16.859375
185                    -17.937500
...                           ...
30328                  -18.625000
30329                  -19.359375
30339                  -29.359375
30356                  -17.656250
30381                  -22.843750

[1521 rows x 3 columns]

In [13]:
left_tail_df = left_tail_df.sort_values("Cells_Number_Object_Number").reset_index(drop=True)
left_tail_df

,InChICode_standardised,SMILES,Cells_Number_Object_Number
0,InChI=1S/C23H34O5/c1-21-7-5-15(24)10-14(21)3-4...,CC12CCC(O)CC1CCC1C2[C@H](O)CC2(C)C(C3=CC(=O)OC...,-50.593750
1,InChI=1S/C29H44O12/c1-13-22(34)23(35)24(36)25(...,CC1OC(O[C@H]2C[C@@H](O)[C@]3(CO)[C@H]4[C@H](O)...,-50.468750
2,InChI=1S/C29H33N3O6S2/c1-21-5-10-26(11-6-21)39...,Cc1ccc(S(=O)(=O)N(C)C[C@H]2Oc3cc(C#Cc4ccncc4)c...,-50.067797
3,InChI=1S/C50H81N4O15P/c1-29(20-22-51)16-14-17-...,COC[C@H]([C@@H](O)[C@@H](O)C(O)=NCC[C@@H](C)c1...,-49.593750
4,InChI=1S/C29H42O10/c1-15-22(32)23(33)24(34)25(...,C[C@@H]1O[C@@H](O[C@H]2CC[C@]3(C=O)C4CC[C@]5(C...,-49.468750
...,...,...,...
1516,InChI=1S/C17H20N4O2/c1-3-10-20-15-13(16(22)21(...,CCCn1c(=O)c2nc(-c3ccccc3)[nH]c2n(CCC)c1=O,-14.382812
1517,InChI=1S/C22H24N2O7/c1-29-14-5-2-12(3-6-14)23-...,COc1ccc(NC(O)=Nc2ccc3c(c2)[C@@H]2C[C@H](CC(=O)...,-14.381082
1518,"InChI=1S/C21H25N3O6S/c1-31(27,28)24-14-2-3-18-...",CS(=O)(=O)Nc1ccc2c(c1)[C@@H]1C[C@@H](CC(O)=NCc...,-14.375000
1519,InChI=1S/C28H36N4O4/c1-19-16-32(20(2)18-33)28(...,C[C@@H]1CN([C@H](C)CO)C(=O)c2cc(C3=CCCCC3)cnc2...,-14.375000
1520,InChI=1S/C34H53N5O5/c1-25-21-39(26(2)24-40)34(...,C[C@@H]1CCCCO[C@H](CN(C)Cc2ccncc2)[C@@H](C)CN(...,-14.359375

In [14]:
left_tail_df.to_csv("Bray_low_cell_count.csv", index=False)